# Generated by Django 2.2.2 on 2019-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporarily_closed', 'Temporarily Closed'), ('defunct', 'Defunct')], default='active', max_length=60),
        ),
    ]
