# Generated by Django 2.2.2 on 2019-06-16 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_identificationbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('identification_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IdentificationBody')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
