# Generated by Django 2.2.2 on 2019-06-16 22:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190616_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='min_age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Service'),
        ),
    ]
