# Generated by Django 2.2.2 on 2019-06-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190616_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='eligibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Eligibility'),
        ),
    ]
